jwt:
   secretKey: 12345678901234567890123456789012
   refreshKey: 12345678901234567890123456789012


spring:
  datasource:
    url: jdbc:mysql://database1.cjhewj5vji2q.ap-northeast-2.rds.amazonaws.com:3306/milistockdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: xhdtlswndeo!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect

    