jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012




spring:
  datasource:
    url: jdbc:mysql://database-demo.cgd52m8hcvai.ap-northeast-2.rds.amazonaws.com:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: dongha1005!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect